SendNotice/models.py
from . import db


class Eventlist(db.Model):
    __tablename__ = 'eventlist'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    hostname = db.Column(db.String(255))
    ip = db.Column(db.String(255))
    level = db.Column(db.String(255))
    status = db.Column(db.String(255))
    msg = db.Column(db.Text)
    startAt = db.Column(db.DateTime)
    endAt = db.Column(db.DateTime)
    perAt = db.Column(db.Time)
    alertname = db.Column(db.String(255))
    eventid = db.Column(db.Integer)

SendNotice/__init__.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-


from flask import Flask
from flask_sqlalchemy import SQLAlchemy



db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config.from_object('config.TestConfig')
    db.init_app(app)

    from .feishu import feishu
    app.register_blueprint(feishu)
    return app

SendNotice/feishu/__init__.py
from flask import Blueprint
feishu = Blueprint('feishu', __name__)

from . import views
from . import rules

SendNotice/feishu/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import Blueprint, request, render_template, redirect, url_for, jsonify,current_app
from datetime import datetime, timedelta
from ..models import Eventlist
from .. import db
from . import feishu
from .rules import alertRule
import hashlib
import requests
import json



rule = alertRule()


def send_feishu(url, msg):

    headers = {'Content-Type': 'application/json'}

    body = {
        "msg_type": "text",
        "content": {
            "text": msg
        }
    }

    req = requests.post(url, headers=headers, data=json.dumps(body))
    return req.status_code

# 时间转换
def utc_to_cst(utc_time, utc_format="%Y-%m-%dT%H:%M:%S.%fZ", cst_format="%Y-%m-%d %H:%M:%S"):
    timestamp = datetime.strptime(utc_time, utc_format)
    cststamp = timestamp + timedelta(hours=8)
    return datetime.strftime(cststamp, cst_format)

# 持续时间计算
def time_cal(starttime, endtime):
    time_format = "%Y-%m-%d %H:%M:%S"
    startstamp = datetime.strptime(starttime, time_format)
    endstamp = datetime.strptime(endtime, time_format)
    persistenstamp = endstamp - startstamp
    return persistenstamp


@feishu.route("/showalert")
def get_alarm_history():
    if request.method == 'GET':
        num = request.args.get('num',100)
        # 根据eventid去重
        datalist = Eventlist.query.with_entities(Eventlist.eventid,Eventlist.alertname,Eventlist.hostname,Eventlist.ip,Eventlist.level,Eventlist.msg,Eventlist.startAt,Eventlist.endAt,Eventlist.perAt,Eventlist.status).distinct(Eventlist.eventid).order_by(Eventlist.startAt.desc()).limit(num).all()
        linedata = []
        for dataline in datalist:
            data = dict(dataline)
            data['startAt'] = str(data['startAt'])
            data['endAt'] = str(data['endAt'])
            data['perAt'] = str(data['perAt'])
            linedata.append(data)
        # return jsonify(linedata)
        return render_template('alarmhistory.html', datalist=linedata)

# 知悉
@feishu.route('/ack/<eventid>')
def event_confirm(eventid):
    for eventlist in Eventlist.query.filter(Eventlist.eventid == eventid).filter(Eventlist.status == '告警').all():
        # 更新告警记录
        eventlist.status = '知悉'
        db.session.commit()
    return redirect(url_for('feishu.get_alarm_history'))

@feishu.post("/AlertFeishu")
def alert_feishu():
    try:
        data = request.get_json()
        print(data)
        for alert in data.get('alerts'):
            AlertName = alert.get('labels').get('alertname')
            Hostname = alert.get('labels').get('hostname')
            Ip = alert.get('labels').get('instance')
            Value = alert.get('annotations').get('value')
            Level = alert.get('labels').get('severity')
            Msg = alert.get('annotations').get('description')

            # start时间转换
            # 判断报警、恢复状态发送不同模版
            # 报警
            if alert.get('status') == 'firing':
                StartsAt = utc_to_cst(alert.get('startsAt'))
                # 生成事件id
                Eventid = int(str(int(hashlib.md5((AlertName+Hostname+Ip+StartsAt).encode('utf-8')).hexdigest(),16))[-6:])
                # 匹配策略规则是否通过
                rule_pass = rule.firing_rule(AlertName,Eventid)
                if rule_pass:
                    # 写入数据库
                    eventlist = Eventlist(
                        hostname=Hostname,
                        ip=Ip,
                        level=Level,
                        status='告警',
                        msg=Msg,
                        startAt=StartsAt,
                        alertname=AlertName,
                        eventid=Eventid
                    )
                    db.session.add(eventlist)
                    db.session.commit()
                    firing_value = render_template('firing.html', **locals())
                    # 飞书告警
                    req = send_feishu(current_app.config.get('FEISHU_BOT'), firing_value)
                    if req == 200:
                        print('send feishu ok')
                    else:
                        print('send feishu fail')
                else:
                    print('no alarm')

            # 恢复
            elif alert.get('status') == 'resolved':
                StartsAt = utc_to_cst(alert.get('startsAt'))
                EndAt = utc_to_cst(alert.get('endsAt'))
                PersistentAt = time_cal(utc_to_cst(alert.get(
                    'startsAt')), utc_to_cst(alert.get('endsAt')))
                # 生成事件id
                Eventid = int(str(int(hashlib.md5((AlertName+Hostname+Ip+StartsAt).encode('utf-8')).hexdigest(),16))[-6:])

                rule_pass = rule.resolved_rule(AlertName, Eventid)
                if rule_pass:
                    # 查询数据库中告警记录
                    for eventlist in Eventlist.query.filter(Eventlist.eventid == Eventid).all():
                        # 更新告警记录
                        eventlist.status = '恢复'
                        eventlist.endAt = EndAt
                        eventlist.perAt = PersistentAt
                        db.session.commit()
                    resolved_value = render_template('resolved.html', **locals())
                    # 飞书告警
                    req = send_feishu(current_app.config.get('FEISHU_BOT'), resolved_value)
                    if req == 200:
                        print('send feishu ok')
                    else:
                        print('send feishu fail')
                else:
                    print('no data')
        return jsonify({"code": 200, "message": "success"})
    except Exception as e:
        print(e)
        return jsonify({"code": 403, "message": "The data type is wrong"})

SendNotice/templates/alarmhistory.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <title>report</title>
</head>
<h1>告警记录</h1>
    <body>
        <table border="1">
            <tr bgcolor="#0492c2">
              <td>事件id</td>
              <td>事件名称</td>
              <td>主机名</td>
              <td>主机IP</td>
              <td>告警等级</td>
              <td>告警信息</td>
              <td>告警时间</td>
              <td>恢复时间</td>
              <td>持续时间</td>
              <td>告警状态</td>
              <td>确认</td>
            </tr>
            {% for data in datalist %}
                {% if data.status == '告警' %}
                    <tr bgcolor="#f44336">
                        <td>{{data.eventid}}</td>
                        <td>{{data.alertname}}</td>
                        <td>{{data.hostname}}</td>
                        <td>{{data.ip}}</td>
                        <td>{{data.level}}</td>
                        <td>{{data.msg}}</td>
                        <td>{{data.startAt}}</td>
                        <td>{{data.endAt}}</td>
                        <td>{{data.perAt}}</td>
                        <td>{{data.status}}</td>
                        <td><a href="{{ url_for('feishu.event_confirm',eventid=data.eventid) }}">ok</a></td>
                    </tr>
                {% elif data.status == '恢复' %}
                    <tr bgcolor="#b2e342">
                        <td>{{data.eventid}}</td>
                        <td>{{data.alertname}}</td>
                        <td>{{data.hostname}}</td>
                        <td>{{data.ip}}</td>
                        <td>{{data.level}}</td>
                        <td>{{data.msg}}</td>
                        <td>{{data.startAt}}</td>
                        <td>{{data.endAt}}</td>
                        <td>{{data.perAt}}</td>
                        <td >{{data.status}}</td>
                    </tr>
                {% elif data.status == '知悉' %}
                    <tr bgcolor="#ffa500">
                        <td>{{data.eventid}}</td>
                        <td>{{data.alertname}}</td>
                        <td>{{data.hostname}}</td>
                        <td>{{data.ip}}</td>
                        <td>{{data.level}}</td>
                        <td>{{data.msg}}</td>
                        <td>{{data.startAt}}</td>
                        <td>{{data.endAt}}</td>
                        <td>{{data.perAt}}</td>
                        <td >{{data.status}}</td>
                    </tr>                
                {% endif%}
              {% endfor %}
            </table>
            <p>默认显示100条，<a href="{{ url_for('feishu.get_alarm_history',num=1000) }}">显示更多</a></p>
    </body>
</html>

SendNotice/templates/firing.html
| 监控触发报警，主机出现故障 |
告警主机：{{Hostname}}
告警地址：{{Ip}}
监控取值：{{Value}}
告警等级：{{Level}}
当前状态：告警
告警信息：{{Msg|safe}}
告警时间：{{StartsAt}}

SendNotice/templates/resolved.html
| 系统故障修复，主机恢复正常 |
告警主机：{{Hostname}}
告警地址：{{Ip}}
当前状态：恢复
告警信息：{{Msg|safe}}
告警时间：{{StartsAt}}
恢复时间：{{EndAt}}
持续时间：{{PersistentAt}}